### ISSUE TITLE
Object is not a Parser::AST::Node when parse a comment

### ISSUE THREAD

**Issue by zurk** [bblfsh/ruby-driver#19]
Python code to reproduce:
```python
import bblfsh

response = bblfsh.BblfshClient("0.0.0.0:9432").parse(filename="", language="Ruby", contents="#".encode())
print(response)
```

Found it as error while parsing such files: https://github.com/Yelp/yelp-rails-example/blob/master/config/initializers/inflections.rb

**Comment by juanjux** [comment]
Can reproduce this, working on this now.

**Comment by juanjux** [comment]
Should be fixed by the related PR.
